blank_issues_enabled: false
contact_links:
  - name: GitHub Discusssions
    url: https://github.com/vvhybe/odoo-client/discussions
    about: Please ask questions and help each other here!
  - name: Code of Conduct
    url: https://github.com/vvhybe/odoo-client/blob/main/CODE_OF_CONDUCT.md
    about: Please read our code of conduct before participating.
